require('dotenv').config();
const express = require('express');
const cors = require('cors');
const Database = require('better-sqlite3');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const path = require('path');
const app = express();
const PORT = process.env.PORT || 3000;
const JWT_SECRET = process.env.JWT_SECRET || 'helpdesk-secret';
app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));
const db = new Database('helpdesk.db');
db.pragma('journal_mode = WAL');
db.exec(`CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT UNIQUE NOT NULL, email TEXT UNIQUE NOT NULL, password TEXT NOT NULL, role TEXT DEFAULT 'user', created_at DATETIME DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS tickets (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, description TEXT NOT NULL, priority TEXT DEFAULT 'medium', status TEXT DEFAULT 'open', category TEXT DEFAULT 'general', created_by INTEGER NOT NULL, assigned_to INTEGER, resolved_at DATETIME, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (created_by) REFERENCES users(id), FOREIGN KEY (assigned_to) REFERENCES users(id)); CREATE TABLE IF NOT EXISTS ticket_comments (id INTEGER PRIMARY KEY AUTOINCREMENT, ticket_id INTEGER NOT NULL, user_id INTEGER NOT NULL, comment TEXT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (ticket_id) REFERENCES tickets(id), FOREIGN KEY (user_id) REFERENCES users(id));`);
function auth(req, res, next) { const t = req.headers['authorization']?.split(' ')[1]; if (!t) return res.status(401).json({error:'Token required'}); jwt.verify(t, JWT_SECRET, (e, u) => { if(e) return res.status(403).json({error:'Invalid token'}); req.user=u; next(); }); }
function role(...r) { return (req,res,next) => { if(!r.includes(req.user.role)) return res.status(403).json({error:'Forbidden'}); next(); }; }
app.post('/api/auth/register', (req,res) => { const {username,email,password,role}=req.body; if(!username||!email||!password) return res.status(400).json({error:'All fields required'}); try { const r=db.prepare('INSERT INTO users (username,email,password,role) VALUES (?,?,?,?)').run(username,email,bcrypt.hashSync(password,10),role||'user'); const token=jwt.sign({id:r.lastInsertRowid,username,role:role||'user'},JWT_SECRET,{expiresIn:'24h'}); res.status(201).json({message:'Registered',token,user:{id:r.lastInsertRowid,username,email,role:role||'user'}}); } catch(e) { res.status(409).json({error:'User exists'}); } });
app.post('/api/auth/login', (req,res) => { const {username,password}=req.body; const u=db.prepare('SELECT * FROM users WHERE username=?').get(username); if(!u||!bcrypt.compareSync(password,u.password)) return res.status(401).json({error:'Invalid credentials'}); const token=jwt.sign({id:u.id,username:u.username,role:u.role},JWT_SECRET,{expiresIn:'24h'}); res.json({message:'Login successful',token,user:{id:u.id,username:u.username,email:u.email,role:u.role}}); });
app.get('/api/tickets', auth, (req,res) => { const {status,priority,category}=req.query; let q='SELECT t.*,c.username as created_by_name,a.username as assigned_to_name FROM tickets t LEFT JOIN users c ON t.created_by=c.id LEFT JOIN users a ON t.assigned_to=a.id WHERE 1=1'; const p=[]; if(status){q+=' AND t.status=?';p.push(status);} if(priority){q+=' AND t.priority=?';p.push(priority);} if(category){q+=' AND t.category=?';p.push(category);} if(req.user.role==='user'){q+=' AND (t.created_by=? OR t.assigned_to=?)';p.push(req.user.id,req.user.id);} q+=' ORDER BY t.created_at DESC'; const tickets=db.prepare(q).all(...p); res.json({count:tickets.length,tickets}); });
app.get('/api/tickets/:id', auth, (req,res) => { const t=db.prepare('SELECT * FROM tickets WHERE id=?').get(req.params.id); if(!t) return res.status(404).json({error:'Not found'}); const comments=db.prepare('SELECT tc.*,u.username FROM ticket_comments tc JOIN users u ON tc.user_id=u.id WHERE tc.ticket_id=? ORDER BY tc.created_at').all(req.params.id); res.json({ticket:t,comments}); });
app.post('/api/tickets', auth, (req,res) => { const {title,description,priority,category}=req.body; if(!title||!description) return res.status(400).json({error:'Title and description required'}); const r=db.prepare('INSERT INTO tickets (title,description,priority,category,created_by) VALUES (?,?,?,?,?)').run(title,description,priority||'medium',category||'general',req.user.id); res.status(201).json({message:'Created',ticket:db.prepare('SELECT * FROM tickets WHERE id=?').get(r.lastInsertRowid)}); });
app.patch('/api/tickets/:id/status', auth, (req,res) => { const {status}=req.body; if(!['open','in-progress','resolved','closed'].includes(status)) return res.status(400).json({error:'Invalid status'}); const ra=(status==='resolved'||status==='closed')?new Date().toISOString():null; db.prepare('UPDATE tickets SET status=?,resolved_at=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(status,ra,req.params.id); res.json({message:'Updated',ticket:db.prepare('SELECT * FROM tickets WHERE id=?').get(req.params.id)}); });
app.patch('/api/tickets/:id/assign', auth, role('admin','agent'), (req,res) => { const {assigned_to}=req.body; db.prepare("UPDATE tickets SET assigned_to=?,status='in-progress',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(assigned_to,req.params.id); res.json({message:'Assigned',ticket:db.prepare('SELECT * FROM tickets WHERE id=?').get(req.params.id)}); });
app.post('/api/tickets/:id/comments', auth, (req,res) => { const {comment}=req.body; if(!comment) return res.status(400).json({error:'Comment required'}); const r=db.prepare('INSERT INTO ticket_comments (ticket_id,user_id,comment) VALUES (?,?,?)').run(req.params.id,req.user.id,comment); res.status(201).json({message:'Comment added',comment:db.prepare('SELECT tc.*,u.username FROM ticket_comments tc JOIN users u ON tc.user_id=u.id WHERE tc.id=?').get(r.lastInsertRowid)}); });
app.get('/api/dashboard/stats', auth, role('admin','agent'), (req,res) => { res.json({total:db.prepare('SELECT COUNT(*) as c FROM tickets').get().c,open:db.prepare("SELECT COUNT(*) as c FROM tickets WHERE status='open'").get().c,in_progress:db.prepare("SELECT COUNT(*) as c FROM tickets WHERE status='in-progress'").get().c,resolved:db.prepare("SELECT COUNT(*) as c FROM tickets WHERE status='resolved'").get().c,by_priority:db.prepare('SELECT priority,COUNT(*) as count FROM tickets GROUP BY priority').all(),by_category:db.prepare('SELECT category,COUNT(*) as count FROM tickets GROUP BY category').all()}); });
app.get('/api/health', (req,res) => { res.json({status:'healthy',timestamp:new Date().toISOString(),version:'1.0.0'}); });
app.listen(PORT, () => console.log('Help Desk running on http://localhost:'+PORT));
